### ISSUE TITLE
code enhancements

### ISSUE THREAD

**Issue by 0xpeanutbutter** [omar1024/Check-Permissions#2]
Currently the code complexity isn't at its best. There might be alternate ways to implement things

**Comment by Kineolyan** [comment]
Hello, I saw your issue asking for help. Having some experience in Java, I am confident I can help with that.
You are mentionning that the "code complexitity is not at its best". Do you have any axis of improvement in mind?
From what I see, it is mostly single long methods that could be broken into smaller ones. Is that ok with you?

**Comment by 0xpeanutbutter** [comment]
Yes @Kineolyan that would be great

**Comment by Kineolyan** [comment]
Then, I will look at it and notify you when a PR is ready.

**Comment by Kineolyan** [comment]
FYI, I am working on it in this branch, in case you want a preview of the work: https://github.com/Kineolyan/Check-Permissions/tree/refactor-code.

Have a nice evening/day.
